import { test, expect, type BrowserContext } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { parseEnv } from 'node:util';
import { randomUUID, createHmac } from 'node:crypto';
import { Pool } from 'pg';
import { del } from '@vercel/blob';

const env=parseEnv(readFileSync('.env.local','utf8'));
const prod=parseEnv(readFileSync('.env.production.local','utf8'));
if (new URL(env.DATABASE_URL!).hostname.replace('-pooler','')===new URL(prod.DATABASE_URL!).hostname.replace('-pooler','')) throw new Error('Development database only');
if(new URL(process.env.TEST_BASE_URL || 'http://localhost:3198').hostname!=='localhost') throw new Error('Local browser only');
const pool=new Pool({connectionString:env.DATABASE_URL!.replace('sslmode=require','sslmode=verify-full')});
const users=[randomUUID(),randomUUID(),randomUUID()],slug='approvals-'+randomUUID();
let clientId:string;
test.use({actionTimeout:15000,screenshot:'only-on-failure'});
async function login(context:BrowserContext,index:number){
  const token=randomUUID();
  await pool.query('INSERT INTO public."session"(id,token,"userId","expiresAt","createdAt","updatedAt") VALUES($1,$2,$3,now()+interval \'1 hour\',now(),now())',[randomUUID(),token,users[index]]);
  await context.addCookies([{name:'better-auth.session_token',value:encodeURIComponent(token+'.'+createHmac('sha256',env.BETTER_AUTH_SECRET!).update(token).digest('base64')),domain:'localhost',path:'/',httpOnly:true,secure:false,sameSite:'Lax'}]);
}
test.beforeAll(async()=>{
  for(const [index,id] of users.entries()) await pool.query('INSERT INTO public."user"(id,name,email,"emailVerified","createdAt","updatedAt") VALUES($1,$2,$3,true,now(),now())',[id,index===1?'Alex Client':'Approval QA',id+'@example.invalid']);
  await pool.query("UPDATE profiles SET role='admin' WHERE id=$1",[users[0]]);
});
test.afterAll(async()=>{
  if(clientId){
    const paths=(await pool.query('SELECT storage_path FROM item_versions WHERE item_id IN (SELECT id FROM items WHERE client_id=$1)',[clientId])).rows.map(row=>row.storage_path);
    if(paths.length) await del(paths,{token:env.BLOB_READ_WRITE_TOKEN});
    await pool.query('DELETE FROM approval_requests WHERE client_id=$1',[clientId]);
    await pool.query('UPDATE items SET current_version_id=NULL WHERE client_id=$1',[clientId]);
    await pool.query('DELETE FROM item_versions WHERE item_id IN (SELECT id FROM items WHERE client_id=$1)',[clientId]);
    for(const table of ['events','memberships','items','folders','tracks']) await pool.query(`DELETE FROM ${table} WHERE client_id=$1`,[clientId]);
    await pool.query('DELETE FROM clients WHERE id=$1',[clientId]);
  }
  await pool.query('DELETE FROM profiles WHERE id=ANY($1::text[])',[users]);
  await pool.query('DELETE FROM public."user" WHERE id=ANY($1::text[])',[users]);
  await pool.end();
});

test('clients approve versioned plans and authorise launch scope; changed sources require fresh consent',async({page,context,browser})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  page.on('dialog',dialog=>dialog.accept());
  await login(context,0);
  await page.goto('/admin');
  await page.getByLabel('Company name').fill('Approval Studio QA');
  await page.getByLabel('Workspace slug').fill(slug);
  await page.getByRole('button',{name:'Create client'}).click();
  await expect(page).toHaveURL(/\/admin\/clients\//);
  clientId=page.url().split('/').pop()!;
  await expect(page.getByLabel('Choose files to upload')).toBeEnabled();
  await pool.query('INSERT INTO memberships(client_id,profile_id) VALUES($1,$2)',[clientId,users[1]]);
  const checkpoints=(await pool.query('SELECT id,approval_kind FROM tracks WHERE client_id=$1 AND approval_kind IS NOT NULL',[clientId])).rows;
  expect(checkpoints.map(row=>row.approval_kind).sort()).toEqual(['launch','plan']);
  const planId=checkpoints.find(row=>row.approval_kind==='plan').id,launchId=checkpoints.find(row=>row.approval_kind==='launch').id;
  const plan=page.locator('#track-'+planId),launch=page.locator('#track-'+launchId);
  await plan.locator(':scope>summary').click();
  await expect(plan).toContainText('Upload and publish a plan document');
  const html='<!doctype html><html><head><title>Approved project plan</title></head><body><h1>Plan version one</h1><p>Build a five-page site.</p></body></html>';
  await page.getByLabel('Choose files to upload').setInputFiles({name:'plan.html',mimeType:'text/html',buffer:Buffer.from(html)});
  await expect(page.getByText('1 file added as drafts.',{exact:false})).toBeVisible({timeout:60000});
  const content=page.locator('.content-row').filter({hasText:'Approved project plan'});
  await content.locator(':scope>summary').click();
  await content.getByLabel('Share with client',{exact:true}).check();
  await content.getByRole('button',{name:'Save & publish',exact:true}).click();
  await expect(content.locator(':scope>summary .badge')).toContainText('Published');
  const item=(await pool.query('SELECT id,current_version_id FROM items WHERE client_id=$1',[clientId])).rows[0];
  if (await plan.getAttribute('open') === null) await plan.locator(':scope>summary').click();
  await page.screenshot({path:'.shipstudio/approvals-admin-before-request.png',fullPage:true});
  await plan.getByLabel('Deliverable to review',{exact:true}).selectOption(item.id);
  await plan.getByLabel('Version or release label').fill('Plan v1');
  await plan.getByLabel('What the client is approving').fill('Five-page site, agreed sitemap and content model. Approval allows the build to begin.');
  await plan.getByRole('button',{name:'Request plan approval',exact:true}).click();
  await expect(plan.locator('.approval-badge').first()).toHaveText('Approval requested');
  const memberContext=await browser.newContext(),strangerContext=await browser.newContext();
  await login(memberContext,1);await login(strangerContext,2);
  const member=await memberContext.newPage(),stranger=await strangerContext.newPage();
  member.on('pageerror',error=>errors.push(error.message));
  await stranger.goto('/c/'+slug);
  await expect(stranger.locator('.approval-card')).toHaveCount(0);
  await member.goto('/c/'+slug);
  const card=member.getByRole('article',{name:'Plan approval request 1',exact:true});
  await expect(card).toBeVisible();
  await expect(card.getByRole('link',{name:'Review the requested version'})).toHaveAttribute('href','/items/'+item.id+'?version='+item.current_version_id);
  const popupPromise=memberContext.waitForEvent('page');
  await card.getByRole('link',{name:'Review the requested version'}).click();
  const popup=await popupPromise;
  await expect(popup.frameLocator('iframe').getByRole('heading',{name:'Plan version one'})).toBeVisible();
  await popup.close();
  await card.getByRole('button',{name:'Approve plan',exact:true}).click();
  await expect(card.getByRole('alert')).toHaveText('Tick the confirmation before approving.');
  await card.getByLabel('Comment',{exact:false}).fill('The scope is right. Please proceed.');
  await card.getByRole('checkbox').check();
  await card.getByRole('button',{name:'Approve plan',exact:true}).click();
  await expect(card.locator('.approval-badge')).toHaveText('Approved');
  await expect(card).toContainText('Approved by Alex Client');
  await expect(card).toContainText('The scope is right. Please proceed.');
  const receipt=(await pool.query('SELECT * FROM approval_requests WHERE track_id=$1',[planId])).rows[0];
  expect(receipt.responded_by).toBe(users[1]);expect(receipt.version_id).toBe(item.current_version_id);
  await page.reload();await expect(page.getByLabel('Choose files to upload')).toBeEnabled();
  await plan.locator(':scope>summary').click();
  await expect(plan).toContainText('Approved by Alex Client');
  await content.locator(':scope>summary').click();
  await content.getByLabel('Choose replacement file').setInputFiles({name:'plan.html',mimeType:'text/html',buffer:Buffer.from(html.replace('version one','version two'))});
  await expect(content.getByText('New version saved.',{exact:false})).toBeVisible({timeout:60000});
  await member.reload();
  const memberPlan=member.locator('.progress-spine>li').nth(2);
  if (await memberPlan.locator(':scope>details').getAttribute('open') === null) await memberPlan.locator(':scope>details>summary').click();
  await expect(card.locator('.approval-badge')).toHaveText('Fresh approval needed');
  await expect(card).toContainText('Approved by Alex Client');
  await expect(card.getByRole('button',{name:'Approve plan'})).toHaveCount(0);
  await plan.getByLabel('Deliverable to review',{exact:true}).selectOption(item.id);
  await plan.getByLabel('Version or release label').fill('Plan v2');
  await plan.getByLabel('What the client is approving').fill('Updated sitemap and navigation for the same five-page site.');
  await plan.getByRole('button',{name:'Request plan approval',exact:true}).click();
  await expect(plan.getByRole('article',{name:'Plan approval request 2'})).toBeVisible();
  await member.reload();
  const fresh=member.getByRole('article',{name:'Plan approval request 2',exact:true});
  await fresh.getByLabel('Comment',{exact:false}).fill('Please restore the contact page in the navigation.');
  await fresh.getByRole('button',{name:'Request changes',exact:true}).click();
  await expect(fresh.locator('.approval-badge')).toHaveText('Changes requested');
  // Launch uses a specific staging release and explicit DNS/traffic scope.
  await page.locator('#content summary').filter({hasText:'Add a link'}).click();
  const linkForm=page.locator('#content details').filter({hasText:'Add link draft'}).locator('form');
  await linkForm.getByLabel('Title',{exact:true}).fill('Launch candidate');
  await linkForm.getByLabel('URL',{exact:true}).fill('https://example.com/staging-release-1');
  await linkForm.getByRole('button',{name:'Add link draft'}).click();
  await expect(page.getByText('Link added as a draft.')).toBeVisible();
  const linkRow=page.locator('.content-row').filter({hasText:'Launch candidate'});
  await linkRow.locator(':scope>summary').click();
  await linkRow.getByLabel('Share with client',{exact:true}).check();
  await linkRow.getByRole('button',{name:'Save & publish',exact:true}).click();
  await expect(linkRow.locator(':scope>summary .badge')).toContainText('Published');
  const site=(await pool.query("SELECT id FROM items WHERE client_id=$1 AND type='link'",[clientId])).rows[0].id;
  await launch.locator(':scope>summary').click();
  await launch.getByLabel('Deliverable to review',{exact:true}).selectOption(site);
  await launch.getByLabel('Version or release label').fill('Launch candidate 1');
  await launch.getByLabel('Launch scope and DNS changes').fill('Launch release 1 at example.com. Update the apex A record and www CNAME, then switch traffic to the reviewed site. Keep email DNS records unchanged.');
  await launch.getByRole('button',{name:'Request launch permission',exact:true}).click();
  await expect(launch.locator('.approval-badge').first()).toHaveText('Approval requested');
  await member.reload();
  const launchCard=member.getByRole('article',{name:'Permission to launch request 1',exact:true});
  await expect(launchCard).toContainText('DNS changes');
  await expect(launchCard).toContainText('Update the apex A record');
  await expect(launchCard.getByRole('button',{name:'Authorise launch',exact:true})).toBeEnabled();
  await member.screenshot({path:'.shipstudio/approvals-client-desktop.png',fullPage:true});
  await member.setViewportSize({width:390,height:844});
  await member.screenshot({path:'.shipstudio/approvals-client-mobile.png',fullPage:true});
  expect(await member.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  // A pending browser view cannot answer after an admin withdraws the request.
  await launch.getByRole('button',{name:'Withdraw request',exact:true}).click();
  await expect(launch.locator('.approval-badge').first()).toHaveText('Withdrawn');
  await launchCard.getByRole('checkbox').check();
  await launchCard.getByRole('button',{name:'Authorise launch',exact:true}).click();
  await expect(launchCard.getByRole('alert')).toContainText('Your response was not saved');
  await launch.getByLabel('Deliverable to review',{exact:true}).selectOption(site);
  await launch.getByLabel('Version or release label').fill('Launch candidate 1 confirmed');
  await launch.getByLabel('Launch scope and DNS changes').fill('Launch release 1 at example.com. Update the apex A record and www CNAME, then switch traffic.');
  await launch.getByRole('button',{name:'Request launch permission',exact:true}).click();
  await expect(launch.getByRole('article',{name:'Permission to launch request 2'})).toBeVisible();
  await member.reload();
  const launchFresh=member.getByRole('article',{name:'Permission to launch request 2',exact:true});
  await launchFresh.getByRole('checkbox').check();
  await launchFresh.getByRole('button',{name:'Authorise launch',exact:true}).click();
  await expect(launchFresh.locator('.approval-badge')).toHaveText('Approved');
  await expect(launchFresh).toContainText('KOODOS will carry out the agreed launch and DNS changes');
  expect((await pool.query('SELECT status FROM tracks WHERE id=$1',[launchId])).rows[0].status).toBe('not_started');
  await page.reload();await expect(page.getByLabel('Choose files to upload')).toBeEnabled();
  await launch.locator(':scope>summary').click();
  await expect(launch).toContainText('Approved by Alex Client');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'.shipstudio/approvals-admin-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await pool.query('DELETE FROM memberships WHERE client_id=$1',[clientId]);
  await member.reload();await expect(member.locator('.approval-card')).toHaveCount(0);
  expect(errors).toEqual([]);
  await memberContext.close();await strangerContext.close();
});
