import { test, expect, type BrowserContext, type Route } from '@playwright/test';
import { readFileSync, existsSync } from 'node:fs';
import { parseEnv } from 'node:util';
import { randomUUID, createHmac } from 'node:crypto';
import { Pool } from 'pg';
import { del } from '@vercel/blob';

const local=parseEnv(readFileSync('.env.local','utf8'));
const databaseUrl=local.DATABASE_URL!,secret=local.BETTER_AUTH_SECRET!;
if(!databaseUrl || !secret || !local.BLOB_READ_WRITE_TOKEN)throw new Error('Development database, auth secret, and private Blob token are required.');
const base=process.env.TEST_BASE_URL || 'http://localhost:3198';
if(new URL(base).hostname!=='localhost')throw new Error('These tests run only against localhost and the development database.');
if(existsSync('.env.production.local') && parseEnv(readFileSync('.env.production.local','utf8')).DATABASE_URL===databaseUrl)throw new Error('Refusing to test production database.');
const pool=new Pool({connectionString:databaseUrl.replace('sslmode=require','sslmode=verify-full')});
const run=randomUUID(), users=[randomUUID(),randomUUID(),randomUUID()];
let clientId:string;
async function login(context: BrowserContext, index:number) {
  const token=randomUUID();
  await pool.query('INSERT INTO public."session"(id,token,"userId","expiresAt","createdAt","updatedAt") VALUES($1,$2,$3,now()+interval \'1 hour\',now(),now())',[randomUUID(),token,users[index]]);
  const value=encodeURIComponent(token+'.'+createHmac('sha256',secret).update(token).digest('base64'));
  await context.addCookies([{name:'better-auth.session_token',value,domain:'localhost',path:'/',httpOnly:true,secure:false,sameSite:'Lax'}]);
}
test.beforeAll(async()=>{
  for(let i=0;i<users.length;i++) {
    await pool.query('INSERT INTO public."user"(id,name,email,"emailVerified","createdAt","updatedAt") VALUES($1,$2,$3,true,now(),now())',[users[i],'Content QA '+i,`${users[i]}@example.invalid`]);
  }
  await pool.query("UPDATE profiles SET role='admin' WHERE id=$1",[users[0]]);
});
test.afterAll(async()=>{
  if(clientId) {
    const paths=(await pool.query('SELECT storage_path FROM item_versions WHERE item_id IN (SELECT id FROM items WHERE client_id=$1)',[clientId])).rows.map(r=>r.storage_path);
    if(paths.length)await del(paths,{token:local.BLOB_READ_WRITE_TOKEN});
    await pool.query('UPDATE items SET current_version_id=NULL WHERE client_id=$1',[clientId]);
    await pool.query('DELETE FROM item_versions WHERE item_id IN (SELECT id FROM items WHERE client_id=$1)',[clientId]);
    for(const table of ['events','memberships','items','folders'])await pool.query(`DELETE FROM ${table} WHERE client_id=$1`,[clientId]);
    await pool.query('DELETE FROM clients WHERE id=$1',[clientId]);
  }
  await pool.query('DELETE FROM events WHERE actor_id=ANY($1::text[])',[users]);
  await pool.query('DELETE FROM profiles WHERE id=ANY($1::text[])',[users]);
  await pool.query('DELETE FROM public."user" WHERE id=ANY($1::text[])',[users]);
  await pool.end();
});
test('admin delivers private versioned content; only members see published items',async({page,context,browser})=>{
  const policyErrors: string[] = [];
  page.on('console', message => {
    if (message.text().includes('Content Security Policy')) policyErrors.push(message.text());
  });
  await login(context,0);
  await page.goto('/admin');
  await page.getByLabel('Company name').fill('Content QA '+run);
  await page.getByLabel('Workspace slug').fill('qa-'+run);
  await page.getByRole('button',{name:'Create client'}).click();
  await expect(page).toHaveURL(/\/admin\/clients\//);
  clientId=page.url().split('/').pop()!;
  await pool.query('INSERT INTO memberships(client_id,profile_id) VALUES($1,$2)',[clientId,users[1]]);
  await page.getByLabel('New folder name').fill('Reports');
  await page.getByRole('button',{name:'Add folder',exact:true}).click();
  await expect(page.getByRole('button',{name:'Drag Reports to reorder'})).toBeVisible();
  await page.locator('#content select').first().selectOption({label:'Reports'});
  const html='<!doctype html><html><head><title>QA interactive report</title></head><body><h1>Version one</h1><button id="count">Count</button><p id="result">0</p><script>document.getElementById("count").addEventListener("click",()=>document.getElementById("result").textContent="1");try{parent.document.body.dataset.leaked="yes"}catch{document.body.dataset.isolated="yes"}</script></body></html>';
  await test.step('a stalled Blob transfer times out and allows retry', async () => {
    let received!: (route: Route) => void;
    const pending = new Promise<Route>(resolve => { received = resolve; });
    const endpoint = 'https://vercel.com/api/blob/**';
    await page.route(endpoint, route => { received(route); });
    await page.getByLabel('Choose files to upload').setInputFiles({name:'stalled.html',mimeType:'text/html',buffer:Buffer.from(html)});
    const request = await pending;
    await expect(page.locator('.upload-panel').getByRole('alert')).toHaveText('Transferring the file timed out. Please retry.', {timeout: 50_000});
    await expect(page.getByLabel('Choose files to upload')).toBeEnabled();
    await expect(page.getByLabel('Upload into')).toBeEnabled();
    await request.abort();
    await page.unroute(endpoint);
    expect((await pool.query('SELECT id FROM items WHERE client_id=$1',[clientId])).rowCount).toBe(0);
  });
  await page.getByLabel('Choose files to upload').setInputFiles({name:'report.html',mimeType:'text/html',buffer:Buffer.from(html)});
  await expect(page.getByText('1 file added as drafts.',{exact:false})).toBeVisible({timeout:60000});
  let item=(await pool.query('SELECT * FROM items WHERE client_id=$1',[clientId])).rows[0];
  expect(item.published_at).toBeNull();
  const memberContext=await browser.newContext(),strangerContext=await browser.newContext();
  await login(memberContext,1);await login(strangerContext,2);
  const member=await memberContext.newPage(),stranger=await strangerContext.newPage();
  await member.goto('/c/qa-'+run);
  await expect(member.getByText('QA interactive report',{exact:true})).toHaveCount(0);
  expect((await memberContext.request.get(base+'/api/items/'+item.id+'/file')).status()).toBe(404);
  await page.locator('.content-row summary').first().click();
  await page.locator('.publication-panel').screenshot({path:'.shipstudio/qa-publish-draft.png'});
  await page.getByRole('link',{name:'Preview item'}).click();
  await expect(page.frameLocator('iframe').getByRole('heading',{name:'Version one'})).toBeVisible({timeout:30000});
  await page.frameLocator('iframe').getByRole('button',{name:'Count'}).click();
  await expect(page.frameLocator('iframe').locator('#result')).toHaveText('1');
  await expect(page.locator('body')).not.toHaveAttribute('data-leaked','yes');
  await expect(page.frameLocator('iframe').locator('body')).toHaveAttribute('data-isolated','yes');
  await page.screenshot({path:'.shipstudio/qa-artifact.png',fullPage:true});
  await page.getByRole('link',{name:'Back to manage Content QA '+run}).click();
  await page.locator('.content-row summary').first().click();
  await expect(page.getByRole('button',{name:'Save draft',exact:true})).toBeVisible();
  await page.getByLabel('Share with client',{exact:true}).check();
  await page.getByRole('button',{name:'Save & publish',exact:true}).click();
  await expect(page.locator('.content-row summary .badge')).toHaveText('Published · visible to client');
  await member.reload();
  await expect(member.getByRole('heading',{name:'QA interactive report'})).toBeVisible();
  await test.step('visibility controls explain and save unpublishing', async () => {
    await page.getByLabel('Share with client',{exact:true}).uncheck();
    await page.getByRole('button',{name:'Save & unpublish',exact:true}).click();
    await expect(page.locator('.content-row summary .badge')).toHaveText('Draft \u00b7 hidden from client');
    await member.reload();
    await expect(member.getByRole('heading',{name:'QA interactive report'})).toHaveCount(0);
    await page.getByLabel('Share with client',{exact:true}).check();
    await page.getByRole('button',{name:'Save & publish',exact:true}).click();
    await expect(page.locator('.content-row summary .badge')).toHaveText('Published \u00b7 visible to client');
    await member.reload();
    await expect(member.getByRole('heading',{name:'QA interactive report'})).toBeVisible();
  });
  const signed=await memberContext.request.get(base+'/api/items/'+item.id+'/file');
  expect(signed.ok()).toBeTruthy();
  const signedBody=await signed.json();
  const unsigned=new URL(signedBody.url);unsigned.search='';
  expect((await fetch(unsigned)).ok).toBeFalsy();
  expect((await strangerContext.request.get(base+'/api/items/'+item.id+'/file')).status()).toBe(404);
  await stranger.goto('/admin');
  await expect(stranger.getByRole('heading',{name:'Your clients, together.'})).toHaveCount(0);
  const oldVersion=item.current_version_id;
  await page.getByLabel('Version note').fill('Second edition');
  await page.getByLabel('Choose replacement file').setInputFiles({name:'report.html',mimeType:'text/html',buffer:Buffer.from(html.replace('Version one','Version two'))});
  await expect(page.getByText('New version saved.',{exact:false})).toBeVisible({timeout:60000});
  item=(await pool.query('SELECT * FROM items WHERE id=$1',[item.id])).rows[0];
  expect(item.current_version_id).not.toBe(oldVersion);
  await member.goto('/items/'+item.id);
  await expect(member.frameLocator('iframe').getByRole('heading',{name:'Version two'})).toBeVisible();
  await member.goto('/items/'+item.id+'?version='+oldVersion);
  await expect(member.frameLocator('iframe').getByRole('heading',{name:'Version one'})).toBeVisible();
  await member.getByRole('link',{name:'Back to Content QA '+run,exact:true}).click();
  await expect(member).toHaveURL(/#folder-/);
  await member.getByRole('link',{name:'Back to all workspaces',exact:true}).click();
  await expect(member.getByRole('heading',{name:'Your workspaces.'})).toBeVisible();
  await member.getByRole('link',{name:'Content QA '+run}).click();
  await expect(member.getByRole('heading',{name:'QA interactive report'})).toBeVisible();
  const downloaded=await memberContext.request.get(base+`/api/items/${item.id}/file?version=${oldVersion}&download=1`);
  expect(downloaded.ok()).toBeTruthy();expect(await downloaded.text()).toContain('Version one');
  await page.locator('#content summary').filter({hasText:'Add a link'}).click();
  const linkForm=page.locator('#content details form');
  await linkForm.getByLabel('Title',{exact:true}).fill('Reference link');
  await linkForm.getByLabel('URL',{exact:true}).fill('https://example.com/research');
  await linkForm.getByRole('button',{name:'Add link draft'}).click();
  await expect(page.getByText('Link added as a draft.')).toBeVisible();
  await page.getByLabel('Company name').fill('QA workspace edited');
  await page.getByRole('button',{name:'Save workspace'}).click();
  await expect(page.getByRole('heading',{name:'QA workspace edited'})).toBeVisible();
  await page.screenshot({path:'.shipstudio/qa-admin.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'.shipstudio/qa-admin-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  await page.setViewportSize({width:1280,height:900});
  page.on('dialog',dialog=>dialog.accept());
  await page.locator('#folders').getByRole('button',{name:'Archive',exact:true}).click();
  await member.goto('/items/'+item.id);
  await expect(member.getByRole('heading',{name:'QA interactive report'})).toHaveCount(0);
  expect((await memberContext.request.get(base+'/api/items/'+item.id+'/file')).status()).toBe(404);
  await page.locator('#folders summary').filter({hasText:'Archived folders'}).click();
  await page.getByRole('button',{name:'Restore folder'}).click();
  await expect(page.getByRole('button',{name:'Drag Reports to reorder'})).toBeVisible();
  await member.goto('/items/'+item.id);
  await expect(member.frameLocator('iframe').getByRole('heading',{name:'Version two'})).toBeVisible();
  await pool.query('DELETE FROM memberships WHERE client_id=$1 AND profile_id=$2',[clientId,users[1]]);
  expect((await memberContext.request.get(base+'/api/items/'+item.id+'/file')).status()).toBe(404);
  await memberContext.close();await strangerContext.close();
  expect(policyErrors, 'Uploads and artifact previews must satisfy the portal CSP').toEqual([]);
});
