import { test, expect, type BrowserContext } from '@playwright/test';
import { readFileSync, existsSync } from 'node:fs';
import { parseEnv } from 'node:util';
import { randomUUID, createHmac } from 'node:crypto';
import { Pool } from 'pg';
import { del } from '@vercel/blob';

const local = parseEnv(readFileSync('.env.local', 'utf8'));
const base = process.env.TEST_BASE_URL || 'http://localhost:3198';
if (new URL(base).hostname !== 'localhost') throw new Error('Local tests only');
if (existsSync('.env.production.local') && new URL(parseEnv(readFileSync('.env.production.local','utf8')).DATABASE_URL!).hostname === new URL(local.DATABASE_URL!).hostname) throw new Error('Refusing production database');
const pool = new Pool({ connectionString:local.DATABASE_URL!.replace('sslmode=require','sslmode=verify-full') });
const users = [randomUUID(), randomUUID(), randomUUID()];
const slug = 'projects-'+randomUUID();
let clientId: string;
async function login(context: BrowserContext, index: number) {
  const token = randomUUID();
  await pool.query('INSERT INTO public."session"(id,token,"userId","expiresAt","createdAt","updatedAt") VALUES($1,$2,$3,now()+interval \'1 hour\',now(),now())', [randomUUID(),token,users[index]]);
  const value = encodeURIComponent(token+'.'+createHmac('sha256',local.BETTER_AUTH_SECRET!).update(token).digest('base64'));
  await context.addCookies([{ name:'better-auth.session_token',value,domain:'localhost',path:'/',httpOnly:true,secure:false,sameSite:'Lax' }]);
}
test.beforeAll(async () => {
  for (const id of users) await pool.query('INSERT INTO public."user"(id,name,email,"emailVerified","createdAt","updatedAt") VALUES($1,$2,$3,true,now(),now())',[id,'Projects QA',id+'@example.invalid']);
  await pool.query("UPDATE profiles SET role='admin' WHERE id=$1",[users[0]]);
});
test.afterAll(async () => {
  for (const id of [clientId].filter(Boolean)) {
    await pool.query('UPDATE projects SET archived_at=NULL WHERE client_id=$1', [id]);
    const paths = (await pool.query('SELECT storage_path FROM item_versions WHERE item_id IN (SELECT id FROM items WHERE client_id=$1)', [id])).rows.map(row => row.storage_path);
    await pool.query('DELETE FROM approval_requests WHERE client_id=$1', [id]);
    await pool.query('UPDATE items SET current_version_id=NULL WHERE client_id=$1', [id]);
    await pool.query('DELETE FROM item_versions WHERE item_id IN (SELECT id FROM items WHERE client_id=$1)', [id]);
    for (const table of ['events','memberships','items','folders','tracks']) await pool.query(`DELETE FROM ${table} WHERE client_id=$1`,[id]);
    await pool.query('DELETE FROM clients WHERE id=$1',[id]);
    if (paths.length) await del(paths, { token: local.BLOB_READ_WRITE_TOKEN });
  }
  await pool.query('DELETE FROM profiles WHERE id=ANY($1::text[])',[users]);
  await pool.query('DELETE FROM public."user" WHERE id=ANY($1::text[])',[users]);
  await pool.end();
});

test('a client can have independent projects, content and work tracks', async ({ page, context, browser }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(context, 0);
  await page.goto('/admin');
  await page.getByLabel('Company name').fill('Projects Studio QA');
  await page.getByLabel('Workspace slug').fill(slug);
  await page.getByRole('button', { name: 'Create client' }).click();
  await expect(page).toHaveURL(/\/admin\/clients\//);
  clientId = page.url().split('/').pop()!;
  await expect(page.getByLabel('Choose files to upload')).toBeEnabled();
  const first = (await pool.query('SELECT id FROM projects WHERE client_id=$1', [clientId])).rows[0].id;
  await pool.query('INSERT INTO memberships(client_id,profile_id) VALUES($1,$2)', [clientId, users[1]]);
  async function addLink(title: string) {
    const details = page.locator('#content details');
    await details.locator('summary').click();
    await details.getByLabel('Title', { exact: true }).fill(title);
    await details.getByLabel('URL', { exact: true }).fill('https://example.com/' + title.replaceAll(' ', '-'));
    await details.getByRole('button', { name: 'Add link draft' }).click();
    await expect(details.getByRole('status')).toHaveText('Link added as a draft.');
    const row = page.locator('.content-row').filter({ hasText: title });
    await row.locator(':scope>summary').click();
    await row.getByLabel('Share with client', { exact: true }).check();
    await row.getByRole('button', { name: 'Save & publish', exact: true }).click();
    await expect(row.locator(':scope>summary .badge')).toContainText('Published');
  }
  await addLink('First project deliverable');
  const projectPanel = page.getByRole('region', { name: 'Projects', exact: true });
  await projectPanel.getByText('Add a project', { exact: true }).click();
  const create = projectPanel.locator('details').filter({ has: page.getByRole('button', { name: 'Create project', exact: true }) });
  await create.getByLabel('Project name', { exact: true }).fill('Website refresh');
  await create.getByLabel('Project description').fill('A separate website project.');
  await create.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page).toHaveURL(/\?project=/);
  const second = new URL(page.url()).searchParams.get('project')!;
  expect(second).not.toBe(first);
  await expect(page.locator('.track-editor')).toHaveCount(7);
  await expect(page.locator('.content-row')).toHaveCount(0);
  const secondTracks = (await pool.query('SELECT id,name FROM tracks WHERE project_id=$1 ORDER BY position', [second])).rows;
  expect(secondTracks.map(t => t.name)).toEqual(['Discovery','Research','Plan','Build','Review','Launch','Operate']);
  // A new project arrives with a folder per delivery stage, each linked to its stage, plus the
  // commercial folder. Operate is ongoing service, not a filing stage, so it gets none.
  const seededFolders = (await pool.query('SELECT name,track_id FROM folders WHERE project_id=$1 ORDER BY position', [second])).rows;
  expect(seededFolders.map(f => f.name)).toEqual(['Discovery','Research','Plan','Build','Review','Launch','Proposals & commercials']);
  expect(seededFolders[0].track_id).toBe(secondTracks[0].id);
  expect(seededFolders[5].track_id).toBe(secondTracks[5].id);
  expect(seededFolders[6].track_id).toBeNull();
  await page.getByLabel('New folder name').fill('Website files');
  await page.getByRole('button', { name: 'Add folder', exact: true }).click();
  const folderRow = page.locator('.folder-row').filter({ has: page.getByLabel('Work track for Website files') });
  await folderRow.getByLabel('Work track for Website files').selectOption(secondTracks[1].id);
  await folderRow.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(folderRow.getByRole('status')).toHaveText('Saved.');
  await addLink('Second project deliverable');
  const secondItem = (await pool.query('SELECT id,project_id FROM items WHERE client_id=$1 AND title=$2', [clientId, 'Second project deliverable'])).rows[0];
  expect(secondItem.project_id).toBe(second);
  await page.getByLabel('Choose files to upload').setInputFiles({ name: 'second-plan.html', mimeType: 'text/html', buffer: Buffer.from('<!doctype html><html><head><title>Second project plan</title></head><body><h1>Website scope</h1></body></html>') });
  await expect(page.getByText('1 file added as drafts.', { exact: false })).toBeVisible({ timeout: 60000 });
  const upload = (await pool.query('SELECT id,project_id,current_version_id FROM items WHERE client_id=$1 AND title=$2', [clientId, 'Second project plan'])).rows[0];
  expect(upload.project_id).toBe(second);
  expect(upload.current_version_id).toBeTruthy();
  const launch = page.locator('#track-' + secondTracks[5].id);
  await launch.locator(':scope>summary').click();
  const choices = await launch.getByLabel('Deliverable to review', { exact: true }).locator('option').allTextContents();
  expect(choices.join(' ')).toContain('Second project deliverable');
  expect(choices.join(' ')).not.toContain('First project deliverable');
  await launch.getByLabel('Deliverable to review', { exact: true }).selectOption(secondItem.id);
  await launch.getByLabel('Version or release label').fill('Release 1');
  await launch.getByLabel('Launch scope and DNS changes').fill('Launch the second project on its reviewed release URL.');
  await launch.getByRole('button', { name: 'Request launch permission', exact: true }).click();
  await expect(launch.locator('.approval-badge').first()).toHaveText('Approval requested');
  const memberContext = await browser.newContext();
  const strangerContext = await browser.newContext();
  try {
    await login(memberContext, 1); await login(strangerContext, 2);
    const member = await memberContext.newPage(), stranger = await strangerContext.newPage();
    member.on('pageerror', error => errors.push(error.message));
    await member.goto('/c/' + slug + '?project=' + first);
    await expect(member.locator('.approval-card')).toHaveCount(0);
    await expect(member.getByRole('heading', { name: 'First project deliverable', exact: true })).toBeVisible();
    await expect(member.getByRole('heading', { name: 'Second project deliverable', exact: true })).toHaveCount(0);
    await member.getByRole('navigation', { name: 'Choose project' }).getByRole('link', { name: 'Website refresh', exact: true }).click();
    await expect(member.getByRole('heading', { name: 'Second project deliverable', exact: true })).toBeVisible();
    await expect(member.getByRole('heading', { name: 'First project deliverable', exact: true })).toHaveCount(0);
    const approval = member.getByRole('article', { name: 'Permission to launch request 1', exact: true });
    await expect(approval).toBeVisible();
    await approval.getByRole('checkbox').check();
    await approval.getByRole('button', { name: 'Authorise launch', exact: true }).click();
    await expect(approval.locator('.approval-badge')).toHaveText('Approved');
    await member.getByRole('link').filter({ has: member.getByRole('heading', { name: 'Second project deliverable' }) }).click();
    await expect(member.getByRole('link', { name: 'Back to Projects Studio QA' })).toHaveAttribute('href', '/c/' + slug + '?project=' + second);
    await stranger.goto('/c/' + slug + '?project=' + second);
    await expect(stranger.getByRole('navigation', { name: 'Choose project' })).toHaveCount(0);
    await page.goto('/admin/board?client=' + slug + '&show=all');
    await expect(page.locator('.board-card')).toHaveCount(12);
    await expect(page.locator('.board-card-top').filter({ hasText: 'Website refresh' })).toHaveCount(6);
    await page.locator('.board-card').filter({ hasText: 'Website refresh' }).first().getByRole('link', { name: 'Discovery', exact: true }).click();
    await expect(page).toHaveURL(new RegExp('project=' + second));
    await page.setViewportSize({ width: 390, height: 844 });
    await member.setViewportSize({ width: 390, height: 844 });
    await member.goto('/c/' + slug + '?project=' + second);
    for (const view of [page, member]) expect(await view.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: '.shipstudio/projects-admin-mobile.png', fullPage: true });
    await member.screenshot({ path: '.shipstudio/projects-client-mobile.png', fullPage: true });
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.screenshot({ path: '.shipstudio/projects-admin-desktop.png', fullPage: true });
    const panel = page.getByRole('region', { name: 'Projects', exact: true });
    await panel.getByText('Project settings', { exact: true }).click();
    page.once('dialog', dialog => dialog.accept());
    await panel.getByRole('button', { name: 'Archive project', exact: true }).click();
    await expect(page).toHaveURL('/admin/clients/' + clientId);
    await member.reload();
    await expect(member.getByRole('heading', { name: 'Second project deliverable', exact: true })).toHaveCount(0);
    await member.goto('/items/' + secondItem.id);
    await expect(member.getByRole('heading', { name: 'Second project deliverable', exact: true })).toHaveCount(0);
    expect((await memberContext.request.get(base + '/api/items/' + upload.id + '/render')).status()).toBe(404);
    await panel.getByText('Archived projects', { exact: true }).click();
    await panel.getByRole('button', { name: 'Restore Website refresh', exact: true }).click();
    await expect(page).toHaveURL('/admin/clients/' + clientId + '?project=' + second);
    await member.goto('/c/' + slug + '?project=' + second);
    await expect(member.getByRole('heading', { name: 'Second project deliverable', exact: true })).toBeVisible();
    await pool.query('DELETE FROM memberships WHERE client_id=$1 AND profile_id=$2', [clientId, users[1]]);
    await member.reload();
    await expect(member.getByRole('navigation', { name: 'Choose project' })).toHaveCount(0);
    expect(errors).toEqual([]);
  } finally { await memberContext.close(); await strangerContext.close(); }
});
