import { test, expect, type BrowserContext } from '@playwright/test';
import { readFileSync, existsSync } from 'node:fs';
import { parseEnv } from 'node:util';
import { randomUUID, createHmac } from 'node:crypto';
import { Pool } from 'pg';

const local = parseEnv(readFileSync('.env.local', 'utf8'));
const base = process.env.TEST_BASE_URL || 'http://localhost:3198';
if (new URL(base).hostname !== 'localhost') throw new Error('Local tests only');
if (existsSync('.env.production.local') && new URL(parseEnv(readFileSync('.env.production.local','utf8')).DATABASE_URL!).hostname === new URL(local.DATABASE_URL!).hostname) throw new Error('Refusing production database');
const pool = new Pool({ connectionString:local.DATABASE_URL!.replace('sslmode=require','sslmode=verify-full') });
const users = [randomUUID(), randomUUID(), randomUUID()];
const slug = 'tracks-'+randomUUID();
let clientId: string;
let otherId: string;
async function login(context: BrowserContext, index: number) {
  const token = randomUUID();
  await pool.query('INSERT INTO public."session"(id,token,"userId","expiresAt","createdAt","updatedAt") VALUES($1,$2,$3,now()+interval \'1 hour\',now(),now())', [randomUUID(),token,users[index]]);
  const value = encodeURIComponent(token+'.'+createHmac('sha256',local.BETTER_AUTH_SECRET!).update(token).digest('base64'));
  await context.addCookies([{ name:'better-auth.session_token',value,domain:'localhost',path:'/',httpOnly:true,secure:false,sameSite:'Lax' }]);
}
test.beforeAll(async () => {
  for (const id of users) await pool.query('INSERT INTO public."user"(id,name,email,"emailVerified","createdAt","updatedAt") VALUES($1,$2,$3,true,now(),now())',[id,'Tracks QA',id+'@example.invalid']);
  await pool.query("UPDATE profiles SET role='admin' WHERE id=$1",[users[0]]);
});
test.afterAll(async () => {
  for (const id of [clientId,otherId].filter(Boolean)) {
    for (const table of ['events','memberships','items','folders','tracks']) await pool.query(`DELETE FROM ${table} WHERE client_id=$1`,[id]);
    await pool.query('DELETE FROM clients WHERE id=$1',[id]);
  }
  await pool.query('DELETE FROM profiles WHERE id=ANY($1::text[])',[users]);
  await pool.query('DELETE FROM public."user" WHERE id=ANY($1::text[])',[users]);
  await pool.end();
});

test('work tracks report progress, preserve filing and support the cross-client board', async ({ page,context,browser }) => {
  const errors: string[] = [];
  page.on('pageerror',error=>errors.push(error.message));
  await login(context,0);
  await page.goto('/admin');
  await page.getByLabel('Company name').fill('Rooted Education QA');
  await page.getByLabel('Workspace slug').fill(slug);
  await page.getByRole('button',{name:'Create client'}).click();
  await expect(page).toHaveURL(/\/admin\/clients\//);
  clientId = page.url().split('/').pop()!;
  await expect(page.getByLabel('Choose files to upload')).toBeEnabled();
  await pool.query('INSERT INTO memberships(client_id,profile_id) VALUES($1,$2)',[clientId,users[1]]);
  const tracks = (await pool.query('SELECT * FROM tracks WHERE client_id=$1 ORDER BY position',[clientId])).rows;
  expect(tracks.map(t=>t.name)).toEqual(['Discovery','Research','Plan','Build','Review','Launch','Operate']);
  expect(tracks.filter(t=>t.recurring).map(t=>t.name)).toEqual(['Operate']);
  const research = page.locator('#track-'+tracks[1].id);
  await research.locator('summary').click();
  await research.getByLabel('Status',{exact:true}).selectOption('waiting_on_client');
  await research.getByLabel('Client update').fill('Please share your priority markets so we can finish the research pack.');
  await research.getByRole('button',{name:'Save track',exact:true}).click();
  await expect(research.getByRole('status')).toContainText('Track updated');
  await page.getByLabel('New folder name').fill('Research reports');
  await page.getByRole('button',{name:'Add folder',exact:true}).click();
  const folderRow = page.locator('.folder-row').filter({has:page.getByLabel('Work track for Research reports')});
  await folderRow.getByLabel('Work track for Research reports').selectOption(tracks[1].id);
  await folderRow.getByRole('button',{name:'Save',exact:true}).click();
  await expect(folderRow.getByRole('status')).toHaveText('Saved.');
  const folder = (await pool.query('SELECT id,track_id FROM folders WHERE client_id=$1',[clientId])).rows[0];
  expect(folder.track_id).toBe(tracks[1].id);
  // Counts must exclude drafts, archived items and archived folders even in admin preview.
  await pool.query("INSERT INTO items(client_id,folder_id,type,title,url,published_at) VALUES($1,$2,'link','Research pack','https://example.com',now()),($1,$2,'link','Secret draft','https://example.com',NULL)",[clientId,folder.id]);
  await pool.query("INSERT INTO items(client_id,folder_id,type,title,url,published_at,archived_at) VALUES($1,$2,'link','Archived report','https://example.com',now(),now())",[clientId,folder.id]);
  const archivedFolder = (await pool.query("INSERT INTO folders(client_id,name,track_id,archived_at) VALUES($1,'Hidden reports',$2,now()) RETURNING id",[clientId,tracks[1].id])).rows[0].id;
  await pool.query("INSERT INTO items(client_id,folder_id,type,title,url,published_at) VALUES($1,$2,'link','Hidden folder report','https://example.com',now())",[clientId,archivedFolder]);
  await pool.query("UPDATE tracks SET status='done' WHERE id=$1",[tracks[0].id]);
  await pool.query("UPDATE tracks SET status='in_progress' WHERE id=$1",[tracks[6].id]);
  const memberContext = await browser.newContext();
  const strangerContext = await browser.newContext();
  await login(memberContext,1); await login(strangerContext,2);
  const member = await memberContext.newPage(), stranger = await strangerContext.newPage();
  member.on('pageerror',error=>errors.push(error.message));
  await member.goto('/c/'+slug);
  await expect(member.getByRole('heading',{name:'Where things stand'})).toBeVisible();
  await expect(member.locator('.progress-current')).toHaveText('Stage 2 of 6 · Research');
  await expect(member.locator('.progress-spine>li')).toHaveCount(6);
  await expect(member.locator('.client-ongoing')).toContainText('Operate');
  await expect(member.locator('.progress-spine')).not.toContainText('Operate');
  await expect(member.getByText('Waiting on you',{exact:true})).toBeVisible();
  const researchDetail = member.locator('.progress-spine>li').nth(1);
  await expect(researchDetail).toContainText('1 shared deliverable');
  await expect(researchDetail.locator('time')).toBeVisible();
  await expect(member.getByText('Secret draft',{exact:true})).toHaveCount(0);
  await expect(member.getByText('Hidden folder report',{exact:true})).toHaveCount(0);
  await researchDetail.getByRole('link',{name:'Research reports'}).click();
  await expect(member).toHaveURL(/#folder-/);
  await stranger.goto('/c/'+slug);
  await expect(stranger.getByRole('heading',{name:'Where things stand'})).toHaveCount(0);
  await member.goto('/admin/board');
  await expect(member.getByRole('heading',{name:'The work in motion.'})).toHaveCount(0);
  // A second client proves filtering is not just cosmetic.
  otherId = (await pool.query("INSERT INTO clients(name,slug) VALUES('Studio B QA',$1) RETURNING id",['other-'+slug])).rows[0].id;
  await pool.query("INSERT INTO tracks(client_id,name,status) VALUES($1,'Other research','in_progress')",[otherId]);
  await page.goto('/admin/board');
  await expect(page.locator('.board-column')).toHaveCount(3);
  await expect(page.locator('.board-card')).toHaveCount(2);
  await expect(page.locator('.board-ongoing')).toContainText('Operate');
  await page.getByRole('link',{name:/Rooted Education QA 2/}).click();
  await expect(page).toHaveURL(new RegExp('client='+slug));
  await expect(page.locator('.board-card')).toHaveCount(1);
  await page.getByLabel('Status for Rooted Education QA · Research').selectOption('done');
  await expect(page.locator('.board-card')).toHaveCount(0);
  expect((await pool.query('SELECT status FROM tracks WHERE id=$1',[tracks[1].id])).rows[0].status).toBe('done');
  await page.getByRole('link',{name:'Show all stages',exact:true}).click();
  await expect(page.locator('.board-column')).toHaveCount(5);
  await expect(page.locator('.board-card')).toHaveCount(6);
  const drag = page.getByRole('button',{name:'Drag Rooted Education QA Research to change status',exact:true});
  await drag.dragTo(page.getByRole('region',{name:'In progress',exact:true}));
  await expect(page.getByLabel('Status for Rooted Education QA · Research')).toHaveValue('in_progress');
  await page.getByRole('link',{name:'Show live work',exact:true}).click();
  await expect(page.locator('.board-column')).toHaveCount(3);
  await page.screenshot({path:'.shipstudio/tracks-board-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'.shipstudio/tracks-board-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.goto('/admin/clients/'+clientId);
  await expect(page.getByLabel('Choose files to upload')).toBeEnabled();
  await page.locator('#track-'+tracks[1].id+' summary').click();
  await page.screenshot({path:'.shipstudio/tracks-admin-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.setViewportSize({width:1280,height:900});
  await page.screenshot({path:'.shipstudio/tracks-admin-desktop.png',fullPage:true});
  // Rename, reorder, archive/restore, and add a recurring track.
  await research.getByLabel('Track name',{exact:true}).fill('Market research');
  await research.getByRole('button',{name:'Save track',exact:true}).click();
  await expect(research.locator('summary')).toContainText('Market research');
  await research.getByRole('button',{name:'Move Market research up',exact:true}).click();
  await expect(page.locator('.track-editor').first()).toHaveAttribute('id','track-'+tracks[1].id);
  page.on('dialog',dialog=>dialog.accept());
  await research.getByRole('button',{name:'Archive track',exact:true}).click();
  await expect(page.locator('#track-'+tracks[1].id)).toHaveCount(0);
  await member.goto('/c/'+slug);
  await expect(member.locator('.progress-spine>li')).toHaveCount(5);
  await expect(member.getByRole('heading',{name:'Research pack',exact:true})).toBeVisible();
  await page.getByText('Archived tracks (1)',{exact:true}).click();
  await page.getByRole('button',{name:'Restore track',exact:true}).click();
  await expect(page.locator('#track-'+tracks[1].id)).toBeVisible();
  await page.getByText('Add a work track',{exact:true}).click();
  const add = page.locator('#tracks .sub-panel').filter({hasText:'Add a work track'});
  await add.getByLabel('New track name').fill('Content care');
  await add.getByLabel('Ongoing service',{exact:true}).check();
  await add.getByRole('button',{name:'Add track',exact:true}).click();
  await expect(page.locator('.track-editor').last()).toContainText('Content care');
  await member.goto('/c/'+slug);
  await expect(member.locator('.progress-spine>li')).toHaveCount(6);
  await expect(member.locator('.client-ongoing')).toContainText('Content care');
  await member.screenshot({path:'.shipstudio/tracks-client-desktop.png',fullPage:true});
  await member.setViewportSize({width:390,height:844});
  await member.screenshot({path:'.shipstudio/tracks-client-mobile.png',fullPage:true});
  expect(await member.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await pool.query("UPDATE tracks SET status='done' WHERE client_id=$1 AND recurring=false",[clientId]);
  await member.reload();
  await expect(member.locator('.progress-current')).toHaveText('Delivery complete.');
  await expect(member.locator('.progress-count')).toHaveText('6 of 6 stages complete');
  await expect(member.locator('.client-ongoing')).toContainText('In progress');
  await pool.query('DELETE FROM memberships WHERE client_id=$1',[clientId]);
  await member.reload();
  await expect(member.getByRole('heading',{name:'Where things stand'})).toHaveCount(0);
  expect(errors).toEqual([]);
  await memberContext.close(); await strangerContext.close();
});
