import { loadEnvConfig } from '@next/env';
import { readFileSync } from 'node:fs';
import { parseEnv } from 'node:util';
import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
import { getPool } from '../src/lib/db';
loadEnvConfig(process.cwd(),true);
const prod = parseEnv(readFileSync('.env.production.local','utf8')).DATABASE_URL;
if (new URL(prod!).hostname.replace('-pooler','') === new URL(process.env.DATABASE_URL!).hostname.replace('-pooler','')) throw new Error('Development only');

async function main() {
  const pool=getPool(),db=await pool.connect();
  try {
    await db.query('BEGIN');
    const admin=randomUUID(),member=randomUUID(),other=randomUUID(),second=randomUUID();
    for (const id of [admin,member,other,second]) await db.query('INSERT INTO public."user"(id,name,email,"emailVerified","createdAt","updatedAt") VALUES($1,$2,$3,true,now(),now())',[id,'Approval reviewer',id+'@example.invalid']);
    await db.query("UPDATE profiles SET role='admin' WHERE id=$1",[admin]);
    const client=(await db.query("INSERT INTO clients(name,slug) VALUES('Approval test',$1) RETURNING id",['approval-'+randomUUID()])).rows[0].id;
    const otherClient=(await db.query("INSERT INTO clients(name,slug) VALUES('Other',$1) RETURNING id",['other-'+randomUUID()])).rows[0].id;
    await db.query('INSERT INTO memberships(client_id,profile_id) VALUES($1,$2),($1,$3),($4,$5)',[client,member,second,otherClient,other]);
    const track=(await db.query("INSERT INTO tracks(client_id,name,approval_kind) VALUES($1,'Plan','plan') RETURNING id",[client])).rows[0].id;
    const launch=(await db.query("INSERT INTO tracks(client_id,name,approval_kind) VALUES($1,'Launch','launch') RETURNING id",[client])).rows[0].id;
    const item=(await db.query("INSERT INTO items(client_id,type,title,published_at) VALUES($1,'artifact','The plan',now()) RETURNING id",[client])).rows[0].id;
    const version=(await db.query("INSERT INTO item_versions(item_id,storage_path,mime_type,size_bytes) VALUES($1,$2,'text/html',42) RETURNING id",[item,randomUUID()])).rows[0].id;
    await db.query('UPDATE items SET current_version_id=$1 WHERE id=$2',[version,item]);
    const otherItem=(await db.query("INSERT INTO items(client_id,type,title,url,published_at) VALUES($1,'link','Other site','https://example.com',now()) RETURNING id",[otherClient])).rows[0].id;
    const site=(await db.query("INSERT INTO items(client_id,type,title,url,published_at) VALUES($1,'link','Staging','https://example.com/release-1',now()) RETURNING id",[client])).rows[0].id;
    await db.query('SET LOCAL ROLE koodos_app');
    const actor=async(id:string)=>{await db.query("SELECT set_config('app.user_id',$1,true)",[id]);};
    const denied=async(sql:string,params:unknown[],message:string)=>{
      await db.query('SAVEPOINT denied'); await assert.rejects(db.query(sql,params),message); await db.query('ROLLBACK TO SAVEPOINT denied');
    };
    await actor(member);
    await denied('SELECT private.request_approval($1,$2,$3,$4)',[track,item,'v1','Plan scope'],'Client cannot request own approval');
    await actor(admin);
    await denied('SELECT private.request_approval($1,$2,$3,$4)',[launch,otherItem,'v1','Launch scope'],'Cross-client source rejected');
    await denied('SELECT private.request_approval($1,$2,$3,$4)',[track,site,'v1','Plan scope'],'Plan requires immutable uploaded version');
    await db.query('UPDATE items SET published_at=NULL WHERE id=$1',[item]);
    await denied('SELECT private.request_approval($1,$2,$3,$4)',[track,item,'v1','Plan scope'],'Draft source rejected');
    await db.query('UPDATE items SET published_at=now() WHERE id=$1',[item]);
    const request=(await db.query('SELECT private.request_approval($1,$2,$3,$4) AS id',[track,item,'Plan v1','Approved scope'])).rows[0].id;
    await denied('UPDATE approval_requests SET scope=$1 WHERE id=$2',['Tampered',request],'Admin cannot rewrite snapshot');
    await denied('DELETE FROM approval_requests WHERE id=$1',[request],'Runtime cannot erase history');
    await denied('SELECT private.respond_to_approval($1,$2,$3)',[request,'approved',''],'Admin cannot approve on behalf of client');
    await actor(other);
    assert.equal((await db.query('SELECT id FROM approval_requests WHERE id=$1',[request])).rowCount,0,'Other client cannot read request');
    await denied('SELECT private.respond_to_approval($1,$2,$3)',[request,'approved',''],'Other client cannot respond');
    await actor(member);
    await denied('SELECT private.respond_to_approval($1,$2,$3)',[request,'invalid',''],'Invalid decision rejected');
    await db.query('SELECT private.respond_to_approval($1,$2,$3)',[request,'approved','Looks right']);
    const receipt=(await db.query('SELECT * FROM approval_requests WHERE id=$1',[request])).rows[0];
    assert.equal(receipt.version_id,version); assert.equal(receipt.scope,'Approved scope');
    assert.equal(receipt.responder_email,member+'@example.invalid'); assert.equal(receipt.responder_name,'Approval reviewer');
    assert.ok(receipt.responded_at); assert.equal(receipt.response_comment,'Looks right');
    await denied('UPDATE approval_requests SET decision=$1 WHERE id=$2',['changes_requested',request],'Client cannot rewrite response');
    await actor(second);
    await denied('SELECT private.respond_to_approval($1,$2,$3)',[request,'changes_requested','Late second response'],'First response closes request');
    await actor(admin);
    const replacement=(await db.query("INSERT INTO item_versions(item_id,storage_path,mime_type,size_bytes) VALUES($1,$2,'text/html',43) RETURNING id",[item,randomUUID()])).rows[0].id;
    await db.query('UPDATE items SET current_version_id=$1 WHERE id=$2',[replacement,item]);
    assert.ok((await db.query('SELECT invalidated_at FROM approval_requests WHERE id=$1',[request])).rows[0].invalidated_at,'Replacement invalidates consent');
    const fresh=(await db.query('SELECT private.request_approval($1,$2,$3,$4) AS id',[track,item,'Plan v2','Updated scope'])).rows[0].id;
    assert.ok((await db.query('SELECT superseded_at FROM approval_requests WHERE id=$1',[request])).rows[0].superseded_at);
    await actor(member);
    await db.query('SELECT private.respond_to_approval($1,$2,$3)',[fresh,'changes_requested','Change navigation']);
    await actor(admin);
    const launchRequest=(await db.query('SELECT private.request_approval($1,$2,$3,$4) AS id',[launch,site,'Release 1','Switch example.com A record and traffic'])).rows[0].id;
    assert.match((await db.query('SELECT consent_text FROM approval_requests WHERE id=$1',[launchRequest])).rows[0].consent_text,/DNS/);
    await db.query('SELECT private.withdraw_approval($1)',[launchRequest]);
    await actor(member);
    await denied('SELECT private.respond_to_approval($1,$2,$3)',[launchRequest,'approved',''],'Withdrawn request rejected');
    await actor(admin);
    const latest=(await db.query('SELECT private.request_approval($1,$2,$3,$4) AS id',[launch,site,'Release 2','Switch example.com A record and traffic'])).rows[0].id;
    await db.query("UPDATE items SET url='https://example.com/release-2' WHERE id=$1",[site]);
    await actor(member);
    await denied('SELECT private.respond_to_approval($1,$2,$3)',[latest,'approved',''],'Changed staging link rejected');
    await actor(admin);
    const final=(await db.query('SELECT private.request_approval($1,$2,$3,$4) AS id',[launch,site,'Release 3','Switch example.com A record and traffic'])).rows[0].id;
    await db.query('DELETE FROM memberships WHERE client_id=$1 AND profile_id=$2',[client,member]);
    await actor(member);
    assert.equal((await db.query('SELECT id FROM approval_requests WHERE client_id=$1',[client])).rowCount,0,'Revocation hides history');
    await denied('SELECT private.respond_to_approval($1,$2,$3)',[final,'approved',''],'Revoked member cannot respond');
    console.log('PASS: approval snapshots, client identity, immutable history, tenant isolation, write restrictions, first response wins, replacement invalidation, changes requested, withdrawal and revocation.');
  } finally {await db.query('ROLLBACK');db.release();await pool.end();}
}
main().catch(error=>{console.error(error.message);process.exitCode=1;});
